"""legg til ukedager på User

Revision ID: 05d7bc783f69
Revises: 
Create Date: 2026-07-26 10:34:11.934717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d7bc783f69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monday', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tuesday', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wednesdaysday', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('thursday', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('friday', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('saturday', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sunday', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sunday')
        batch_op.drop_column('saturday')
        batch_op.drop_column('friday')
        batch_op.drop_column('thursday')
        batch_op.drop_column('wednesdaysday')
        batch_op.drop_column('tuesday')
        batch_op.drop_column('monday')

    # ### end Alembic commands ###
