"""endre public til visibility

Revision ID: 08db6bbc4ba5
Revises: ddd6d961dfa5
Create Date: 2026-07-29 19:42:48.576297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08db6bbc4ba5'
down_revision = 'ddd6d961dfa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_meal')
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.String(length=20), nullable=False, server_default='private'))
        batch_op.drop_column('public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('visibility')

    op.create_table('_alembic_tmp_meal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ingredients', sa.TEXT(), nullable=False),
    sa.Column('recipe', sa.TEXT(), nullable=False),
    sa.Column('time', sa.VARCHAR(length=15), nullable=False),
    sa.Column('image_file', sa.VARCHAR(length=20), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('visibility', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
