"""Lagt til uke 2

Revision ID: 15f4b8e0f507
Revises: c738c74a5e48
Create Date: 2026-07-28 21:22:36.666987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f4b8e0f507'
down_revision = 'c738c74a5e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monday2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tuesday2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wednesday2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('thursday2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('friday2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('saturday2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sunday2', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sunday2')
        batch_op.drop_column('saturday2')
        batch_op.drop_column('friday2')
        batch_op.drop_column('thursday2')
        batch_op.drop_column('wednesday2')
        batch_op.drop_column('tuesday2')
        batch_op.drop_column('monday2')

    # ### end Alembic commands ###
