"""added expiration_date

Revision ID: 3514a55e4d06
Revises: 59af1353ef92
Create Date: 2026-08-02 17:24:06.803114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3514a55e4d06'
down_revision = '59af1353ef92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_item', schema=None) as batch_op:
        batch_op.drop_column('expiration_date')

    # ### end Alembic commands ###
