"""initial schema

Revision ID: 3e730118cbef
Revises: 
Create Date: 2026-08-01 11:14:41.763770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e730118cbef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('monday', sa.Integer(), nullable=True),
    sa.Column('tuesday', sa.Integer(), nullable=True),
    sa.Column('wednesday', sa.Integer(), nullable=True),
    sa.Column('thursday', sa.Integer(), nullable=True),
    sa.Column('friday', sa.Integer(), nullable=True),
    sa.Column('saturday', sa.Integer(), nullable=True),
    sa.Column('sunday', sa.Integer(), nullable=True),
    sa.Column('monday2', sa.Integer(), nullable=True),
    sa.Column('tuesday2', sa.Integer(), nullable=True),
    sa.Column('wednesday2', sa.Integer(), nullable=True),
    sa.Column('thursday2', sa.Integer(), nullable=True),
    sa.Column('friday2', sa.Integer(), nullable=True),
    sa.Column('saturday2', sa.Integer(), nullable=True),
    sa.Column('sunday2', sa.Integer(), nullable=True),
    sa.Column('shopping_list', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('follow_requests',
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('requested_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requested_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('requester_id', 'requested_id')
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('recipe', sa.Text(), nullable=False),
    sa.Column('time', sa.String(length=15), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('essential', sa.Boolean(), nullable=False),
    sa.Column('substitute', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient')
    op.drop_table('storage_item')
    op.drop_table('push_subscription')
    op.drop_table('meal')
    op.drop_table('followers')
    op.drop_table('follow_requests')
    op.drop_table('user')
    # ### end Alembic commands ###
