"""fjern gammel ingredients-kolonne

Revision ID: 5b77b1afeece
Revises: ac4f8c2705ab
Create Date: 2026-07-30 22:26:48.179742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b77b1afeece'
down_revision = 'ac4f8c2705ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
