"""legg til terms_accepted_at på User

Revision ID: 65b0458b4547
Revises: 3514a55e4d06
Create Date: 2026-08-02 19:02:54.403600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b0458b4547'
down_revision = '3514a55e4d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('terms_accepted_at')

    # ### end Alembic commands ###
