"""bytt substitute_group til substitute

Revision ID: 6819c8cac48a
Revises: 5b77b1afeece
Create Date: 2026-07-30 22:40:46.101862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6819c8cac48a'
down_revision = '5b77b1afeece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('substitute', sa.String(length=100), nullable=True))
        batch_op.drop_column('substitute_group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('substitute_group', sa.INTEGER(), nullable=True))
        batch_op.drop_column('substitute')

    # ### end Alembic commands ###
