"""fikset bug

Revision ID: a846fc359d08
Revises: 05d7bc783f69
Create Date: 2026-07-26 11:27:46.697148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a846fc359d08'
down_revision = '05d7bc783f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wednesday', sa.Integer(), nullable=True))
        batch_op.drop_column('wednesdaysday')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wednesdaysday', sa.INTEGER(), nullable=True))
        batch_op.drop_column('wednesday')

    # ### end Alembic commands ###
