"""lagt till shopping_list

Revision ID: c738c74a5e48
Revises: 40e74a33619e
Create Date: 2026-07-28 20:17:12.896157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c738c74a5e48'
down_revision = '40e74a33619e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shopping_list', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('shopping_list')

    # ### end Alembic commands ###
