"""endre public til visibility

Revision ID: ddd6d961dfa5
Revises: 9fff4a18d10d
Create Date: 2026-07-29 19:35:03.393503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd6d961dfa5'
down_revision = '9fff4a18d10d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.String(length=20), nullable=False, server_default='private'))
        batch_op.drop_column('public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###
